package entity.meuble;

import com.genericdao.GenericDAO;
import com.genericdao.annotation.Column;
import com.genericdao.annotation.Id;
import com.genericdao.annotation.Table;

import exception.QuantiteNegatifZeroException;

@Table(name = "detail_formule_meuble")
public class DetailFormuleMeuble extends GenericDAO {

	@Id(autoGenerated = true)
	@Column(name = "id")
	private Integer id;

	@Column(name = "id_formule_meuble")
	private Integer idFormuleMeuble;

	@Column(name = "id_materiau")
	private Integer idMateriau;

	@Column(name = "quantite")
	private Double quantite;

	public DetailFormuleMeuble() {

	}

	public DetailFormuleMeuble(Integer id, Integer idFormuleMeuble, Integer idMateriau, Double quantite)
			throws Exception {
		setId(id);
		setIdFormuleMeuble(idFormuleMeuble);
		setIdMateriau(idMateriau);
		setQuantite(quantite);

	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setIdFormuleMeuble(Integer idFormuleMeuble) {
		this.idFormuleMeuble = idFormuleMeuble;
	}

	public Integer getIdFormuleMeuble() {
		return idFormuleMeuble;
	}

	public void setIdMateriau(Integer idMateriau) {
		this.idMateriau = idMateriau;
	}

	public Integer getIdMateriau() {
		return idMateriau;
	}

	public void setQuantite(Double quantite) throws Exception {
		if (quantite <= 0) {
			throw new QuantiteNegatifZeroException();
		}
		this.quantite = quantite;
	}

	public Double getQuantite() {
		return quantite;
	}

}