package entity.meuble;

import com.genericdao.*;
import com.genericdao.annotation.*;

import exception.FieldNegatifZeroException;

@Table(name = "detail_employe_meuble")
public class DetailEmployeMeuble extends GenericDAO {

	@Id(autoGenerated = true)
	@Column(name = "id")
	private Integer id;

	@Column(name = "id_formule_meuble")
	private Integer idFormuleMeuble;

	@Column(name = "id_poste")
	private Integer idPoste;

	@Column(name = "id_niveau")
	private Integer idNiveau;

	@Column(name = "nombre")
	private Integer nombre;

	@Column(name = "duree")
	private Double duree;

	public DetailEmployeMeuble() {

	}

	public DetailEmployeMeuble(Integer id, Integer idFormuleMeuble, Integer idPoste, Integer idNiveau, Integer nombre,
			Double duree) throws Exception{
		setId(id);
		setIdFormuleMeuble(idFormuleMeuble);
		setIdPoste(idPoste);
		setIdNiveau(idNiveau);
		setNombre(nombre);
		setDuree(duree);

	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setIdFormuleMeuble(Integer idFormuleMeuble) {
		this.idFormuleMeuble = idFormuleMeuble;
	}

	public Integer getIdFormuleMeuble() {
		return idFormuleMeuble;
	}

	public void setIdPoste(Integer idPoste) {
		this.idPoste = idPoste;
	}

	public Integer getIdPoste() {
		return idPoste;
	}

	public void setIdNiveau(Integer idNiveau) {
		this.idNiveau = idNiveau;
	}

	public Integer getIdNiveau() {
		return idNiveau;
	}

	public void setNombre(Integer nombre) throws Exception{
		if (nombre<=0) {
			throw new FieldNegatifZeroException("Nombre");
		}
		this.nombre = nombre;
	}

	public Integer getNombre() {
		return nombre;
	}

	public void setDuree(Double duree) {
		this.duree = duree;
	}

	public Double getDuree() {
		return duree;
	}

}