package entity.meuble;


import com.genericdao.*;
import com.genericdao.annotation.*;



@Table( name = "detail_vente_meuble" )
public class DetailVenteMeuble extends GenericDAO {

    @Id( autoGenerated = true)
	@Column( name = "id")
	private Integer id;

	@Column( name = "id_vente_meuble")
	private Integer idVenteMeuble;

	@Column( name = "id_formule_meuble")
	private Integer idFormuleMeuble;

	@Column( name = "quantite")
	private Double quantite;

	@Column( name = "prix_unitaire")
	private Double prixUnitaire;

	@Column( name = "prix_total")
	private Double prixTotal;

	

    public DetailVenteMeuble() {

    }

    public DetailVenteMeuble(Integer id, Integer idVenteMeuble, Integer idFormuleMeuble, Double quantite, Double prixUnitaire, Double prixTotal) {
        setId(id);
		setIdVenteMeuble(idVenteMeuble);
		setIdFormuleMeuble(idFormuleMeuble);
		setQuantite(quantite);
		setPrixUnitaire(prixUnitaire);
		setPrixTotal(prixTotal);
		
    }

    public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setIdVenteMeuble(Integer idVenteMeuble) {
		this.idVenteMeuble = idVenteMeuble;
	}

	public Integer getIdVenteMeuble() {
		return idVenteMeuble;
	}

	public void setIdFormuleMeuble(Integer idFormuleMeuble) {
		this.idFormuleMeuble = idFormuleMeuble;
	}

	public Integer getIdFormuleMeuble() {
		return idFormuleMeuble;
	}

	public void setQuantite(Double quantite) {
		this.quantite = quantite;
	}

	public Double getQuantite() {
		return quantite;
	}

	public void setPrixUnitaire(Double prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	public Double getPrixUnitaire() {
		return prixUnitaire;
	}

	public void setPrixTotal(Double prixTotal) {
		this.prixTotal = prixTotal;
	}

	public Double getPrixTotal() {
		return prixTotal;
	}

	

}