package entity.meuble;

import java.sql.Connection;
import java.sql.PreparedStatement;

import com.genericdao.GenericDAO;
import com.genericdao.annotation.Column;
import com.genericdao.annotation.Id;
import com.genericdao.annotation.Table;

@Table(name = "materiau_possible_style_meuble")
public class MateriauPossibleStyleMeuble extends GenericDAO {

	@Id(autoGenerated = true)
	@Column(name = "id")
	private Integer id;

	@Column(name = "id_style_meuble")
	private Integer idStyleMeuble;

	@Column(name = "id_materiau")
	private Integer idMateriau;

	public MateriauPossibleStyleMeuble() {

	}

	public MateriauPossibleStyleMeuble(Integer id, Integer idStyleMeuble, Integer idMateriau) {
		setId(id);
		setIdStyleMeuble(idStyleMeuble);
		setIdMateriau(idMateriau);

	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setIdStyleMeuble(Integer idStyleMeuble) {
		this.idStyleMeuble = idStyleMeuble;
	}

	public Integer getIdStyleMeuble() {
		return idStyleMeuble;
	}

	public void setIdMateriau(Integer idMateriau) {
		this.idMateriau = idMateriau;
	}

	public Integer getIdMateriau() {
		return idMateriau;
	}

	public static MateriauPossibleStyleMeuble seelctByIdMateriauAndIdStyleMeuble(Connection connection,Integer idMateriau,Integer idStyleMeuble) throws Exception {
		String query = "select * from materiau_possible_style_meuble where id_style_meuble = ? and id_materiau = ?";
		PreparedStatement preparedStatement = connection.prepareStatement(query);
		preparedStatement.setInt(1, idStyleMeuble);
		preparedStatement.setInt(2, idMateriau);
		return MateriauPossibleStyleMeuble.selectOneByPreparedStatement(MateriauPossibleStyleMeuble.class, preparedStatement, connection);
	}

}