package entity.meuble;


import com.genericdao.*;
import com.genericdao.annotation.*;



@Table( name = "materiau_possible_style_meuble" )
public class MateriauPossibleStyleMeuble extends GenericDAO {

    @Id( autoGenerated = true)
	@Column( name = "id")
	private Integer id;

	@Column( name = "id_style_meuble")
	private Integer idStyleMeuble;

	@Column( name = "id_materiau")
	private Integer idMateriau;

	

    public MateriauPossibleStyleMeuble() {

    }

    public MateriauPossibleStyleMeuble(Integer id, Integer idStyleMeuble, Integer idMateriau) {
        setId(id);
		setIdStyleMeuble(idStyleMeuble);
		setIdMateriau(idMateriau);
		
    }

    public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setIdStyleMeuble(Integer idStyleMeuble) {
		this.idStyleMeuble = idStyleMeuble;
	}

	public Integer getIdStyleMeuble() {
		return idStyleMeuble;
	}

	public void setIdMateriau(Integer idMateriau) {
		this.idMateriau = idMateriau;
	}

	public Integer getIdMateriau() {
		return idMateriau;
	}

	

}