package entity.meuble;


import com.genericdao.*;
import com.genericdao.annotation.*;



@Table( name = "style_meuble" )
public class StyleMeuble extends GenericDAO {

    @Id( autoGenerated = true)
	@Column( name = "id")
	private Integer id;

	@Column( name = "nom")
	private String nom;

	

    public StyleMeuble() {

    }

    public StyleMeuble(Integer id, String nom) {
        setId(id);
		setNom(nom);
		
    }

    public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getNom() {
		return nom;
	}

	

}