package entity.materiau;


import com.genericdao.*;
import com.genericdao.annotation.*;



@Table( name = "materiau" )
public class Materiau extends GenericDAO {

    @Id( autoGenerated = true)
	@Column( name = "id")
	private Integer id;

	@Column( name = "nom")
	private String nom;

	@Column( name = "id_type_materiau")
	private Integer idTypeMateriau;

	@Column( name = "description")
	private String description;

	

    public Materiau() {

    }

    public Materiau(Integer id, String nom, Integer idTypeMateriau, String description) {
        setId(id);
		setNom(nom);
		setIdTypeMateriau(idTypeMateriau);
		setDescription(description);
		
    }

    public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getNom() {
		return nom;
	}

	public void setIdTypeMateriau(Integer idTypeMateriau) {
		this.idTypeMateriau = idTypeMateriau;
	}

	public Integer getIdTypeMateriau() {
		return idTypeMateriau;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

	

}